# Generated by Django 2.2.2 on 2019-06-23 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20190623_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='painting',
            name='image',
            field=models.ImageField(upload_to='static/img/painting/'),
        ),
    ]
