# Generated by Django 2.2.2 on 2019-06-24 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_auto_20190623_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='painting',
            name='create_date',
            field=models.DateField(verbose_name='date published'),
        ),
    ]
