# Generated by Django 2.2.2 on 2019-06-24 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_auto_20190624_2113'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Painting',
            new_name='PaintingModel',
        ),
    ]
