# Generated by Django 2.2.2 on 2019-06-24 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_auto_20190624_2226'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PaintingModel',
            new_name='Paintings',
        ),
    ]
