# Generated by Django 2.2.2 on 2019-06-24 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_auto_20190624_2229'),
    ]

    operations = [
        migrations.AddField(
            model_name='paintings',
            name='details',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='paintings',
            name='title',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='paintings',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='paintings',
            name='image',
            field=models.ImageField(upload_to='portfolio/static/img/paintings_img/'),
        ),
    ]
