# Generated by Django 2.2.2 on 2019-06-24 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_auto_20190624_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paintings',
            name='image',
            field=models.ImageField(upload_to='images/paintings_img/'),
        ),
    ]
